export { default as Feed } from './Feed';
export { default as Mybox } from './Mybox';
export { default as Login } from './Login';
export { default as Notification } from './Notification';
export { default as Post } from './Post';
export { default as Profile } from './Profile';
export { default as ProfileEdit } from './ProfileEdit';
export { default as Welcome } from './Welcome';
export { default as AddFriends } from './AddFriends';
