# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'clientfavomorn' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for clientfavomorn
  pod 'Firebase/Core'
  pod 'Firebase/Auth'

  target 'clientfavomorn-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'react-native-safari-view', :path => '../node_modules/react-native-safari-view'

  end

  target 'clientfavomornTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
